<template>
    <Story title="Icon/Demo">
        <Variant title="default">
            <Icon>
                <img
                    src="https://demo1-ru.webasyst.com/wa-data/public/hub/categories/3/ipng.png"
                    alt=""
                >
            </Icon>
        </Variant>
        <Variant title="sized">
            <p>
                <Icon size="smallest">
                    <img
                        src="https://demo1-ru.webasyst.com/wa-data/public/hub/categories/3/ipng.png"
                        alt=""
                    >
                </Icon>
                <Icon size="smaller">
                    <img
                        src="https://demo1-ru.webasyst.com/wa-data/public/hub/categories/3/ipng.png"
                        alt=""
                    >
                </Icon>
                <Icon size="small">
                    <img
                        src="https://demo1-ru.webasyst.com/wa-data/public/hub/categories/3/ipng.png"
                        alt=""
                    >
                </Icon>
                <Icon size="large">
                    <img
                        src="https://demo1-ru.webasyst.com/wa-data/public/hub/categories/3/ipng.png"
                        alt=""
                    >
                </Icon>
                <Icon size="larger">
                    <img
                        src="https://demo1-ru.webasyst.com/wa-data/public/hub/categories/3/ipng.png"
                        alt=""
                    >
                </Icon>
                <Icon size="largest">
                    <img
                        src="https://demo1-ru.webasyst.com/wa-data/public/hub/categories/3/ipng.png"
                        alt=""
                    >
                </Icon>
            </p>
            <p>
                <Icon size="8">
                    <img
                        src="https://demo1-ru.webasyst.com/wa-data/public/hub/categories/3/ipng.png"
                        alt=""
                    >
                </Icon>
                <Icon size="10">
                    <img
                        src="https://demo1-ru.webasyst.com/wa-data/public/hub/categories/3/ipng.png"
                        alt=""
                    >
                </Icon>
                <Icon size="12">
                    <img
                        src="https://demo1-ru.webasyst.com/wa-data/public/hub/categories/3/ipng.png"
                        alt=""
                    >
                </Icon>
                <Icon size="14">
                    <img
                        src="https://demo1-ru.webasyst.com/wa-data/public/hub/categories/3/ipng.png"
                        alt=""
                    >
                </Icon>
                <Icon size="16">
                    <img
                        src="https://demo1-ru.webasyst.com/wa-data/public/hub/categories/3/ipng.png"
                        alt=""
                    >
                </Icon>
                <Icon size="18">
                    <img
                        src="https://demo1-ru.webasyst.com/wa-data/public/hub/categories/3/ipng.png"
                        alt=""
                    >
                </Icon>
                <Icon size="20">
                    <img
                        src="https://demo1-ru.webasyst.com/wa-data/public/hub/categories/3/ipng.png"
                        alt=""
                    >
                </Icon>
                <Icon size="22">
                    <img
                        src="https://demo1-ru.webasyst.com/wa-data/public/hub/categories/3/ipng.png"
                        alt=""
                    >
                </Icon>
                <Icon size="24">
                    <img
                        src="https://demo1-ru.webasyst.com/wa-data/public/hub/categories/3/ipng.png"
                        alt=""
                    >
                </Icon>
                <Icon size="26">
                    <img
                        src="https://demo1-ru.webasyst.com/wa-data/public/hub/categories/3/ipng.png"
                        alt=""
                    >
                </Icon>
                <Icon size="28">
                    <img
                        src="https://demo1-ru.webasyst.com/wa-data/public/hub/categories/3/ipng.png"
                        alt=""
                    >
                </Icon>
                <Icon size="30">
                    <img
                        src="https://demo1-ru.webasyst.com/wa-data/public/hub/categories/3/ipng.png"
                        alt=""
                    >
                </Icon>
                <Icon size="32">
                    <img
                        src="https://demo1-ru.webasyst.com/wa-data/public/hub/categories/3/ipng.png"
                        alt=""
                    >
                </Icon>
                <Icon size="48">
                    <img
                        src="https://demo1-ru.webasyst.com/wa-data/public/hub/categories/3/ipng.png"
                        alt=""
                    >
                </Icon>
                <Icon size="64">
                    <img
                        src="https://demo1-ru.webasyst.com/wa-data/public/hub/categories/3/ipng.png"
                        alt=""
                    >
                </Icon>
                <Icon size="72">
                    <img
                        src="https://demo1-ru.webasyst.com/wa-data/public/hub/categories/3/ipng.png"
                        alt=""
                    >
                </Icon>
                <Icon size="80">
                    <img
                        src="https://demo1-ru.webasyst.com/wa-data/public/hub/categories/3/ipng.png"
                        alt=""
                    >
                </Icon>
                <Icon size="96">
                    <img
                        src="https://demo1-ru.webasyst.com/wa-data/public/hub/categories/3/ipng.png"
                        alt=""
                    >
                </Icon>
            </p>
        </Variant>
        <Variant title="align baseline">
            <Icon
                size="smallest"
                baseline
            >
                <img
                    src="https://demo1-ru.webasyst.com/wa-data/public/hub/categories/3/ipng.png"
                    alt=""
                >
            </Icon>
            <Icon
                size="smaller"
                baseline
            >
                <img
                    src="https://demo1-ru.webasyst.com/wa-data/public/hub/categories/3/ipng.png"
                    alt=""
                >
            </Icon>
            <Icon
                size="small"
                baseline
            >
                <img
                    src="https://demo1-ru.webasyst.com/wa-data/public/hub/categories/3/ipng.png"
                    alt=""
                >
            </Icon>
            <Icon
                size="large"
                baseline
            >
                <img
                    src="https://demo1-ru.webasyst.com/wa-data/public/hub/categories/3/ipng.png"
                    alt=""
                >
            </Icon>
            <Icon
                size="larger"
                baseline
            >
                <img
                    src="https://demo1-ru.webasyst.com/wa-data/public/hub/categories/3/ipng.png"
                    alt=""
                >
            </Icon>
            <Icon
                size="largest"
                baseline
            >
                <img
                    src="https://demo1-ru.webasyst.com/wa-data/public/hub/categories/3/ipng.png"
                    alt=""
                >
            </Icon>
        </Variant>
        <Variant title="align top">
            <Icon
                size="smallest"
                top
            >
                <img
                    src="https://demo1-ru.webasyst.com/wa-data/public/hub/categories/3/ipng.png"
                    alt=""
                >
            </Icon>
            <Icon
                size="smaller"
                top
            >
                <img
                    src="https://demo1-ru.webasyst.com/wa-data/public/hub/categories/3/ipng.png"
                    alt=""
                >
            </Icon>
            <Icon
                size="small"
                top
            >
                <img
                    src="https://demo1-ru.webasyst.com/wa-data/public/hub/categories/3/ipng.png"
                    alt=""
                >
            </Icon>
            <Icon
                size="large"
                top
            >
                <img
                    src="https://demo1-ru.webasyst.com/wa-data/public/hub/categories/3/ipng.png"
                    alt=""
                >
            </Icon>
            <Icon
                size="larger"
                top
            >
                <img
                    src="https://demo1-ru.webasyst.com/wa-data/public/hub/categories/3/ipng.png"
                    alt=""
                >
            </Icon>
            <Icon
                size="largest"
                top
            >
                <img
                    src="https://demo1-ru.webasyst.com/wa-data/public/hub/categories/3/ipng.png"
                    alt=""
                >
            </Icon>
        </Variant>
        <Variant title="align middle">
            <Icon
                size="smallest"
                middle
            >
                <img
                    src="https://demo1-ru.webasyst.com/wa-data/public/hub/categories/3/ipng.png"
                    alt=""
                >
            </Icon>
            <Icon
                size="smaller"
                middle
            >
                <img
                    src="https://demo1-ru.webasyst.com/wa-data/public/hub/categories/3/ipng.png"
                    alt=""
                >
            </Icon>
            <Icon
                size="small"
                middle
            >
                <img
                    src="https://demo1-ru.webasyst.com/wa-data/public/hub/categories/3/ipng.png"
                    alt=""
                >
            </Icon>
            <Icon
                size="large"
                middle
            >
                <img
                    src="https://demo1-ru.webasyst.com/wa-data/public/hub/categories/3/ipng.png"
                    alt=""
                >
            </Icon>
            <Icon
                size="larger"
                middle
            >
                <img
                    src="https://demo1-ru.webasyst.com/wa-data/public/hub/categories/3/ipng.png"
                    alt=""
                >
            </Icon>
            <Icon
                size="largest"
                middle
            >
                <img
                    src="https://demo1-ru.webasyst.com/wa-data/public/hub/categories/3/ipng.png"
                    alt=""
                >
            </Icon>
        </Variant>
        <Variant title="align shift x">
            <Icon
                size="smallest"
                shift-x="1"
            >
                <img
                    src="https://demo1-ru.webasyst.com/wa-data/public/hub/categories/3/ipng.png"
                    alt=""
                >
            </Icon>
            <Icon
                size="smaller"
                shift-x="2"
            >
                <img
                    src="https://demo1-ru.webasyst.com/wa-data/public/hub/categories/3/ipng.png"
                    alt=""
                >
            </Icon>
            <Icon
                size="small"
                shift-x="4"
            >
                <img
                    src="https://demo1-ru.webasyst.com/wa-data/public/hub/categories/3/ipng.png"
                    alt=""
                >
            </Icon>
            <Icon
                size="large"
                shift-x="6"
            >
                <img
                    src="https://demo1-ru.webasyst.com/wa-data/public/hub/categories/3/ipng.png"
                    alt=""
                >
            </Icon>
            <Icon
                size="larger"
                shift-x="8"
            >
                <img
                    src="https://demo1-ru.webasyst.com/wa-data/public/hub/categories/3/ipng.png"
                    alt=""
                >
            </Icon>
            <Icon
                size="largest"
                shift-x="3"
            >
                <img
                    src="https://demo1-ru.webasyst.com/wa-data/public/hub/categories/3/ipng.png"
                    alt=""
                >
            </Icon>
        </Variant>
        <Variant title="userpic">
            <Icon
                size="smallest"
                userpic
            >
                <img
                    src="https://demo1-ru.webasyst.com/wa-data/public/hub/categories/3/ipng.png"
                    alt=""
                >
            </Icon>
            <Icon
                size="smaller"
                userpic
            >
                <img
                    src="https://demo1-ru.webasyst.com/wa-data/public/hub/categories/3/ipng.png"
                    alt=""
                >
            </Icon>
            <Icon
                size="small"
                userpic
            >
                <img
                    src="https://demo1-ru.webasyst.com/wa-data/public/hub/categories/3/ipng.png"
                    alt=""
                >
            </Icon>
            <Icon
                size="large"
                userpic
            >
                <img
                    src="https://demo1-ru.webasyst.com/wa-data/public/hub/categories/3/ipng.png"
                    alt=""
                >
            </Icon>
            <Icon
                size="larger"
                userpic
            >
                <img
                    src="https://demo1-ru.webasyst.com/wa-data/public/hub/categories/3/ipng.png"
                    alt=""
                >
            </Icon>
            <Icon
                size="largest"
                userpic
            >
                <img
                    src="https://demo1-ru.webasyst.com/wa-data/public/hub/categories/3/ipng.png"
                    alt=""
                >
            </Icon>
        </Variant>
    </Story>
</template>

<script setup lang="ts">
import { Icon } from '@/icon'
</script>
