<template>
    <Story title="Menu/Demo">
        <Variant title="default">
            <Menu>
                <MenuSection bottom-padded>
                    <MenuItem>
                        <MenuItemIcon>
                            ✚
                        </MenuItemIcon>
                        <span>Создать</span>
                    </MenuItem>
                </MenuSection>
                <MenuSection>
                    <MenuItem>
                        <MenuItemIcon>
                            🏠︎
                        </MenuItemIcon>
                        <span>Главная</span>
                    </MenuItem>
                </MenuSection>
                <MenuSection
                    selected
                    rounded
                >
                    <MenuItem>
                        <MenuItemCount>
                            5
                        </MenuItemCount>
                        <MenuItemIcon>
                            ✏️
                        </MenuItemIcon>
                        <span>Блог</span>
                    </MenuItem>
                    <Menu>
                        <MenuSection>
                            <MenuItem>
                                <MenuItemIcon>
                                    👑
                                </MenuItemIcon>
                                <span>Hello</span>
                            </MenuItem>
                        </MenuSection>
                        <MenuSection>
                            <MenuItem>
                                <MenuItemIcon>
                                    <i style="background: orangered;"/>
                                </MenuItemIcon>
                                <span>
                                    Custom icon
                                </span>
                            </MenuItem>
                        </MenuSection>
                        <MenuSection>
                            <MenuItem>
                                <MenuItemIcon>
                                    <i
                                        class="rounded"
                                        style="background: orangered;"
                                    />
                                </MenuItemIcon>
                                <span>Custom icon rounded</span>
                            </MenuItem>
                        </MenuSection>
                        <MenuSection>
                            <MenuItem>
                                <MenuItemIcon>
                                    🌎
                                </MenuItemIcon>
                                <span>World</span>
                            </MenuItem>
                            <Menu>
                                <MenuSection>
                                    <MenuItem>
                                        <MenuItemIcon>
                                            📁
                                        </MenuItemIcon>
                                        <MenuItemCount action>
                                            ⚔️
                                        </MenuItemCount>
                                        <span>Moscow</span>
                                    </MenuItem>
                                </MenuSection>
                                <MenuSection>
                                    <MenuItem>
                                        <MenuItemIcon>
                                            🌲
                                        </MenuItemIcon>
                                        <span>Sochi</span>
                                    </MenuItem>
                                </MenuSection>
                                <MenuSection>
                                    <MenuItem>
                                        <MenuItemIcon>
                                            ⛪
                                        </MenuItemIcon>
                                        <MenuItemCount>
                                            13
                                        </MenuItemCount>
                                        <span>
                                            Saint-Petersburg
                                            <span class="hint">
                                                👑
                                            </span>
                                        </span>
                                    </MenuItem>
                                </MenuSection>
                            </Menu>
                        </MenuSection>
                    </Menu>
                </MenuSection>
                <MenuSection>
                    <MenuItem>
                        <MenuItemCount>
                            23
                        </MenuItemCount>
                        <MenuItemIcon>
                            🪟
                        </MenuItemIcon>
                        <span>Сайт</span>
                    </MenuItem>
                </MenuSection>
                <MenuSection class="tag">
                    <MenuItem>
                        <MenuItemCount>
                            2
                        </MenuItemCount>
                        <MenuItemIcon>
                            #
                        </MenuItemIcon>
                        <span>
                            .tag
                        </span>
                    </MenuItem>
                </MenuSection>
                <MenuSection
                    accented
                    rounded
                >
                    <MenuItem>
                        <MenuItemIcon>
                            🙍🏻‍♂️
                        </MenuItemIcon>
                        <span>
                            Василий
                            <span class="hint">
                                <i class="fas fa-thumbs-up"/>
                            </span>
                        </span>
                    </MenuItem>
                </MenuSection>
                <MenuSection>
                    <MenuItem>
                        <MenuItemCount>
                            <span class="badge">
                                5
                            </span>
                        </MenuItemCount>
                        <MenuItemIcon>
                            🏢
                        </MenuItemIcon>
                        <span>
                            Компания
                            <span class="hint">
                                Текстовая подсказка или даже подсказка с иконкой Font Awesome (нет, это эмоджи) оставляется, как всегда, внутри .hint
                            </span>
                        </span>
                    </MenuItem>
                </MenuSection>
            </Menu>
        </Variant>
        <Variant title="large">
            <Menu large>
                <MenuSection bottom-padded>
                    <MenuItem>
                        <MenuItemIcon>
                            ✚
                        </MenuItemIcon>
                        <span>Создать</span>
                    </MenuItem>
                </MenuSection>
                <MenuSection>
                    <MenuItem>
                        <MenuItemIcon>
                            🏠︎
                        </MenuItemIcon>
                        <span>Главная</span>
                    </MenuItem>
                </MenuSection>
                <MenuSection
                    selected
                    rounded
                >
                    <MenuItem>
                        <MenuItemCount>
                            5
                        </MenuItemCount>
                        <MenuItemIcon>
                            ✏️
                        </MenuItemIcon>
                        <span>Блог</span>
                    </MenuItem>
                    <Menu>
                        <MenuSection>
                            <MenuItem>
                                <MenuItemIcon>
                                    👑
                                </MenuItemIcon>
                                <span>Hello</span>
                            </MenuItem>
                        </MenuSection>
                        <MenuSection>
                            <MenuItem>
                                <MenuItemIcon>
                                    <i style="background: orangered;"/>
                                </MenuItemIcon>
                                <span>
                                    Custom icon
                                </span>
                            </MenuItem>
                        </MenuSection>
                        <MenuSection>
                            <MenuItem>
                                <MenuItemIcon>
                                    <i
                                        class="rounded"
                                        style="background: orangered;"
                                    />
                                </MenuItemIcon>
                                <span>Custom icon rounded</span>
                            </MenuItem>
                        </MenuSection>
                        <MenuSection>
                            <MenuItem>
                                <MenuItemIcon>
                                    🌎
                                </MenuItemIcon>
                                <span>World</span>
                            </MenuItem>
                            <Menu>
                                <MenuSection>
                                    <MenuItem>
                                        <MenuItemIcon>
                                            📁
                                        </MenuItemIcon>
                                        <MenuItemCount action>
                                            ⚔️
                                        </MenuItemCount>
                                        <span>Moscow</span>
                                    </MenuItem>
                                </MenuSection>
                                <MenuSection>
                                    <MenuItem>
                                        <MenuItemIcon>
                                            🌲
                                        </MenuItemIcon>
                                        <span>Sochi</span>
                                    </MenuItem>
                                </MenuSection>
                                <MenuSection>
                                    <MenuItem>
                                        <MenuItemIcon>
                                            ⛪
                                        </MenuItemIcon>
                                        <MenuItemCount>
                                            13
                                        </MenuItemCount>
                                        <span>
                                            Saint-Petersburg
                                            <span class="hint">
                                                👑
                                            </span>
                                        </span>
                                    </MenuItem>
                                </MenuSection>
                            </Menu>
                        </MenuSection>
                    </Menu>
                </MenuSection>
                <MenuSection>
                    <MenuItem>
                        <MenuItemCount>
                            23
                        </MenuItemCount>
                        <MenuItemIcon>
                            🪟
                        </MenuItemIcon>
                        <span>Сайт</span>
                    </MenuItem>
                </MenuSection>
                <MenuSection class="tag">
                    <MenuItem>
                        <MenuItemCount>
                            2
                        </MenuItemCount>
                        <MenuItemIcon>
                            #
                        </MenuItemIcon>
                        <span>
                            .tag
                        </span>
                    </MenuItem>
                </MenuSection>
                <MenuSection
                    accented
                    rounded
                >
                    <MenuItem>
                        <MenuItemIcon>
                            🙍🏻‍♂️
                        </MenuItemIcon>
                        <span>
                            Василий
                            <span class="hint">
                                <i class="fas fa-thumbs-up"/>
                            </span>
                        </span>
                    </MenuItem>
                </MenuSection>
                <MenuSection>
                    <MenuItem>
                        <MenuItemCount>
                            <span class="badge">
                                5
                            </span>
                        </MenuItemCount>
                        <MenuItemIcon>
                            🏢
                        </MenuItemIcon>
                        <span>
                            Компания
                            <span class="hint">
                                Текстовая подсказка или даже подсказка с иконкой Font Awesome (нет, это эмоджи) оставляется, как всегда, внутри .hint
                            </span>
                        </span>
                    </MenuItem>
                </MenuSection>
            </Menu>
        </Variant>
        <Variant title="mobile-friendly">
            <Menu mobile-friendly>
                <MenuSection bottom-padded>
                    <MenuItem>
                        <MenuItemIcon>
                            ✚
                        </MenuItemIcon>
                        <span>Создать</span>
                    </MenuItem>
                </MenuSection>
                <MenuSection>
                    <MenuItem>
                        <MenuItemIcon>
                            🏠︎
                        </MenuItemIcon>
                        <span>Главная</span>
                    </MenuItem>
                </MenuSection>
                <MenuSection
                    selected
                    rounded
                >
                    <MenuItem>
                        <MenuItemCount>
                            5
                        </MenuItemCount>
                        <MenuItemIcon>
                            ✏️
                        </MenuItemIcon>
                        <span>Блог</span>
                    </MenuItem>
                    <Menu>
                        <MenuSection>
                            <MenuItem>
                                <MenuItemIcon>
                                    👑
                                </MenuItemIcon>
                                <span>Hello</span>
                            </MenuItem>
                        </MenuSection>
                        <MenuSection>
                            <MenuItem>
                                <MenuItemIcon>
                                    <i style="background: orangered;"/>
                                </MenuItemIcon>
                                <span>
                                    Custom icon
                                </span>
                            </MenuItem>
                        </MenuSection>
                        <MenuSection>
                            <MenuItem>
                                <MenuItemIcon>
                                    <i
                                        class="rounded"
                                        style="background: orangered;"
                                    />
                                </MenuItemIcon>
                                <span>Custom icon rounded</span>
                            </MenuItem>
                        </MenuSection>
                        <MenuSection>
                            <MenuItem>
                                <MenuItemIcon>
                                    🌎
                                </MenuItemIcon>
                                <span>World</span>
                            </MenuItem>
                            <Menu>
                                <MenuSection>
                                    <MenuItem>
                                        <MenuItemIcon>
                                            📁
                                        </MenuItemIcon>
                                        <MenuItemCount action>
                                            ⚔️
                                        </MenuItemCount>
                                        <span>Moscow</span>
                                    </MenuItem>
                                </MenuSection>
                                <MenuSection>
                                    <MenuItem>
                                        <MenuItemIcon>
                                            🌲
                                        </MenuItemIcon>
                                        <span>Sochi</span>
                                    </MenuItem>
                                </MenuSection>
                                <MenuSection>
                                    <MenuItem>
                                        <MenuItemIcon>
                                            ⛪
                                        </MenuItemIcon>
                                        <MenuItemCount>
                                            13
                                        </MenuItemCount>
                                        <span>
                                            Saint-Petersburg
                                            <span class="hint">
                                                👑
                                            </span>
                                        </span>
                                    </MenuItem>
                                </MenuSection>
                            </Menu>
                        </MenuSection>
                    </Menu>
                </MenuSection>
                <MenuSection>
                    <MenuItem>
                        <MenuItemCount>
                            23
                        </MenuItemCount>
                        <MenuItemIcon>
                            🪟
                        </MenuItemIcon>
                        <span>Сайт</span>
                    </MenuItem>
                </MenuSection>
                <MenuSection class="tag">
                    <MenuItem>
                        <MenuItemCount>
                            2
                        </MenuItemCount>
                        <MenuItemIcon>
                            #
                        </MenuItemIcon>
                        <span>
                            .tag
                        </span>
                    </MenuItem>
                </MenuSection>
                <MenuSection
                    accented
                    rounded
                >
                    <MenuItem>
                        <MenuItemIcon>
                            🙍🏻‍♂️
                        </MenuItemIcon>
                        <span>
                            Василий
                            <span class="hint">
                                <i class="fas fa-thumbs-up"/>
                            </span>
                        </span>
                    </MenuItem>
                </MenuSection>
                <MenuSection>
                    <MenuItem>
                        <MenuItemCount>
                            <span class="badge">
                                5
                            </span>
                        </MenuItemCount>
                        <MenuItemIcon>
                            🏢
                        </MenuItemIcon>
                        <span>
                            Компания
                            <span class="hint">
                                Текстовая подсказка или даже подсказка с иконкой Font Awesome (нет, это эмоджи) оставляется, как всегда, внутри .hint
                            </span>
                        </span>
                    </MenuItem>
                </MenuSection>
            </Menu>
        </Variant>
        <Variant title="ellipsis">
            <Menu ellipsis>
                <MenuSection bottom-padded>
                    <MenuItem>
                        <MenuItemIcon>
                            ✚
                        </MenuItemIcon>
                        <span>Создать</span>
                    </MenuItem>
                </MenuSection>
                <MenuSection>
                    <MenuItem>
                        <MenuItemIcon>
                            🏠︎
                        </MenuItemIcon>
                        <span>Главная</span>
                    </MenuItem>
                </MenuSection>
                <MenuSection
                    selected
                    rounded
                >
                    <MenuItem>
                        <MenuItemCount>
                            5
                        </MenuItemCount>
                        <MenuItemIcon>
                            ✏️
                        </MenuItemIcon>
                        <span>Блог</span>
                    </MenuItem>
                    <Menu>
                        <MenuSection>
                            <MenuItem>
                                <MenuItemIcon>
                                    👑
                                </MenuItemIcon>
                                <span>Hello</span>
                            </MenuItem>
                        </MenuSection>
                        <MenuSection>
                            <MenuItem>
                                <MenuItemIcon>
                                    <i style="background: orangered;"/>
                                </MenuItemIcon>
                                <span>
                                    Custom icon
                                </span>
                            </MenuItem>
                        </MenuSection>
                        <MenuSection>
                            <MenuItem>
                                <MenuItemIcon>
                                    <i
                                        class="rounded"
                                        style="background: orangered;"
                                    />
                                </MenuItemIcon>
                                <span>Custom icon rounded</span>
                            </MenuItem>
                        </MenuSection>
                        <MenuSection>
                            <MenuItem>
                                <MenuItemIcon>
                                    🌎
                                </MenuItemIcon>
                                <span>World</span>
                            </MenuItem>
                            <Menu>
                                <MenuSection>
                                    <MenuItem>
                                        <MenuItemIcon>
                                            📁
                                        </MenuItemIcon>
                                        <MenuItemCount action>
                                            ⚔️
                                        </MenuItemCount>
                                        <span>Moscow</span>
                                    </MenuItem>
                                </MenuSection>
                                <MenuSection>
                                    <MenuItem>
                                        <MenuItemIcon>
                                            🌲
                                        </MenuItemIcon>
                                        <span>Sochi</span>
                                    </MenuItem>
                                </MenuSection>
                                <MenuSection>
                                    <MenuItem>
                                        <MenuItemIcon>
                                            ⛪
                                        </MenuItemIcon>
                                        <MenuItemCount>
                                            13
                                        </MenuItemCount>
                                        <span>
                                            Saint-Petersburg
                                            <span class="hint">
                                                👑
                                            </span>
                                        </span>
                                    </MenuItem>
                                </MenuSection>
                            </Menu>
                        </MenuSection>
                    </Menu>
                </MenuSection>
                <MenuSection>
                    <MenuItem>
                        <MenuItemCount>
                            23
                        </MenuItemCount>
                        <MenuItemIcon>
                            🪟
                        </MenuItemIcon>
                        <span>Сайт</span>
                    </MenuItem>
                </MenuSection>
                <MenuSection class="tag">
                    <MenuItem>
                        <MenuItemCount>
                            2
                        </MenuItemCount>
                        <MenuItemIcon>
                            #
                        </MenuItemIcon>
                        <span>
                            .tag
                        </span>
                    </MenuItem>
                </MenuSection>
                <MenuSection
                    accented
                    rounded
                >
                    <MenuItem>
                        <MenuItemIcon>
                            🙍🏻‍♂️
                        </MenuItemIcon>
                        <span>
                            Василий
                            <span class="hint">
                                <i class="fas fa-thumbs-up"/>
                            </span>
                        </span>
                    </MenuItem>
                </MenuSection>
                <MenuSection>
                    <MenuItem>
                        <MenuItemCount>
                            <span class="badge">
                                5
                            </span>
                        </MenuItemCount>
                        <MenuItemIcon>
                            🏢
                        </MenuItemIcon>
                        <span>
                            Компания
                            <span class="hint">
                                Текстовая подсказка или даже подсказка с иконкой Font Awesome (нет, это эмоджи) оставляется, как всегда, внутри .hint
                            </span>
                        </span>
                    </MenuItem>
                </MenuSection>
            </Menu>
        </Variant>
        <Variant title="break-words">
            <Menu break-words>
                <MenuSection bottom-padded>
                    <MenuItem>
                        <MenuItemIcon>
                            ✚
                        </MenuItemIcon>
                        <span>Создать</span>
                    </MenuItem>
                </MenuSection>
                <MenuSection>
                    <MenuItem>
                        <MenuItemIcon>
                            🏠︎
                        </MenuItemIcon>
                        <span>Главная</span>
                    </MenuItem>
                </MenuSection>
                <MenuSection
                    selected
                    rounded
                >
                    <MenuItem>
                        <MenuItemCount>
                            5
                        </MenuItemCount>
                        <MenuItemIcon>
                            ✏️
                        </MenuItemIcon>
                        <span>Блог</span>
                    </MenuItem>
                    <Menu>
                        <MenuSection>
                            <MenuItem>
                                <MenuItemIcon>
                                    👑
                                </MenuItemIcon>
                                <span>Hello</span>
                            </MenuItem>
                        </MenuSection>
                        <MenuSection>
                            <MenuItem>
                                <MenuItemIcon>
                                    <i style="background: orangered;"/>
                                </MenuItemIcon>
                                <span>
                                    Custom icon
                                </span>
                            </MenuItem>
                        </MenuSection>
                        <MenuSection>
                            <MenuItem>
                                <MenuItemIcon>
                                    <i
                                        class="rounded"
                                        style="background: orangered;"
                                    />
                                </MenuItemIcon>
                                <span>Custom icon rounded</span>
                            </MenuItem>
                        </MenuSection>
                        <MenuSection>
                            <MenuItem>
                                <MenuItemIcon>
                                    🌎
                                </MenuItemIcon>
                                <span>World</span>
                            </MenuItem>
                            <Menu>
                                <MenuSection>
                                    <MenuItem>
                                        <MenuItemIcon>
                                            📁
                                        </MenuItemIcon>
                                        <MenuItemCount action>
                                            ⚔️
                                        </MenuItemCount>
                                        <span>Moscow</span>
                                    </MenuItem>
                                </MenuSection>
                                <MenuSection>
                                    <MenuItem>
                                        <MenuItemIcon>
                                            🌲
                                        </MenuItemIcon>
                                        <span>Sochi</span>
                                    </MenuItem>
                                </MenuSection>
                                <MenuSection>
                                    <MenuItem>
                                        <MenuItemIcon>
                                            ⛪
                                        </MenuItemIcon>
                                        <MenuItemCount>
                                            13
                                        </MenuItemCount>
                                        <span>
                                            Saint-Petersburg
                                            <span class="hint">
                                                👑
                                            </span>
                                        </span>
                                    </MenuItem>
                                </MenuSection>
                            </Menu>
                        </MenuSection>
                    </Menu>
                </MenuSection>
                <MenuSection>
                    <MenuItem>
                        <MenuItemCount>
                            23
                        </MenuItemCount>
                        <MenuItemIcon>
                            🪟
                        </MenuItemIcon>
                        <span>Сайт</span>
                    </MenuItem>
                </MenuSection>
                <MenuSection class="tag">
                    <MenuItem>
                        <MenuItemCount>
                            2
                        </MenuItemCount>
                        <MenuItemIcon>
                            #
                        </MenuItemIcon>
                        <span>
                            .tag
                        </span>
                    </MenuItem>
                </MenuSection>
                <MenuSection
                    accented
                    rounded
                >
                    <MenuItem>
                        <MenuItemIcon>
                            🙍🏻‍♂️
                        </MenuItemIcon>
                        <span>
                            Василий
                            <span class="hint">
                                <i class="fas fa-thumbs-up"/>
                            </span>
                        </span>
                    </MenuItem>
                </MenuSection>
                <MenuSection>
                    <MenuItem>
                        <MenuItemCount>
                            <span class="badge">
                                5
                            </span>
                        </MenuItemCount>
                        <MenuItemIcon>
                            🏢
                        </MenuItemIcon>
                        <span>
                            Компания
                            <span class="hint">
                                Текстовая подсказка или даже подсказка с иконкой Font Awesome (нет, это эмоджи) оставляется, как всегда, внутри .hint
                            </span>
                        </span>
                    </MenuItem>
                </MenuSection>
            </Menu>
        </Variant>
    </Story>
</template>

<script setup lang="ts">
import { Menu, MenuItem, MenuItemCount, MenuItemIcon, MenuSection } from '@/menu'
</script>
